version: "3.8"

services:
  discoveryserver:
    build:
      context: .
      dockerfile: discoveryserver/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservice-networks

  apigateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservice-networks
    depends_on:
      - discoveryserver

networks:
  microservice-networks:
    driver: bridge
