spring:
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:broker:9092}"
    consumer:
      group-id: "${KAFKA_GROUP_ID:default-group}"
  mail:
    host: smtp.gmail.com
    port: 587
    username: namle12122003@gmail.com
    password: lsgh zwbf cvdm hynt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

